name: CI

on:
  push:
    branches: [ gh-pages ]
  pull_request:
    branches: [ gh-pages ]

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    # https://facelessuser.github.io/pyspelling/#usage-in-ci
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install pyspelling
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install pyspelling
        # Install any additional libraries required: additional plugins, documentation building libraries, etc.
    - name: Install aspell
      run: |
        sudo apt-get install aspell aspell-en
    - name: Spell check
      run: |
        python -m pyspelling
